name: "NixOS Configuration Diff"
description: "Shows a diff between NixOS configurations on Pull Requests"
inputs:
  configuration:
    description: "NixOS configuration flake attribute to diff."
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Base Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref }}
        path: nix-diff-base
    
    - name: Checkout PR Repository
      uses: actions/checkout@v4
      with:
        path: nix-diff-target

    - name: Run Diff Script
      run: ${GITHUB_ACTION_PATH}/diff.sh
      id: diff
      shell: bash
      env:
        CONFIGURATION: ${{ inputs.configuration }}
    
    - name: Comment on PR
      uses: https://github.com/thollander/actions-comment-pull-request@v2
      if: ${{ steps.diff.outputs.skip != "true" }}
      with:
        filePath: ${{ steps.diff.outputs.comment_file }}
        comment_tag: "nixos-diff-pr-comment-marker: ${{ inputs.configuration }}"
